// Auto-generated from deckshop.pro + royaleapi data snapshot on 2026-03-10
export const CARD_META = {
  "base_count": 121,
  "evolution_count": 39,
  "hero_count": 10,
  "champion_count": 8,
  "total_entries": 170
};

export const CARDS = [
  {
    "id": "archer-queen",
    "slug": "archer-queen",
    "name": "Archer Queen",
    "elixir": 5,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Champion",
    "variant": "base"
  },
  {
    "id": "archers",
    "slug": "archers",
    "name": "Archers",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "base"
  },
  {
    "id": "arrows",
    "slug": "arrows",
    "name": "Arrows",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Spell",
    "rarity": "Common",
    "variant": "base"
  },
  {
    "id": "baby-dragon",
    "slug": "baby-dragon",
    "name": "Baby Dragon",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "balloon",
    "slug": "balloon",
    "name": "Balloon",
    "elixir": 5,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "bandit",
    "slug": "bandit",
    "name": "Bandit",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Legendary",
    "variant": "base"
  },
  {
    "id": "barbarian-barrel",
    "slug": "barbarian-barrel",
    "name": "Barbarian Barrel",
    "elixir": 2,
    "variable_elixir": false,
    "type": "Spell",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "barbarian-hut",
    "slug": "barbarian-hut",
    "name": "Barbarian Hut",
    "elixir": 6,
    "variable_elixir": false,
    "type": "Building",
    "rarity": "Rare",
    "variant": "base"
  },
  {
    "id": "barbarians",
    "slug": "barbarians",
    "name": "Barbarians",
    "elixir": 5,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "base"
  },
  {
    "id": "bats",
    "slug": "bats",
    "name": "Bats",
    "elixir": 2,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "base"
  },
  {
    "id": "battle-healer",
    "slug": "battle-healer",
    "name": "Battle Healer",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Rare",
    "variant": "base"
  },
  {
    "id": "battle-ram",
    "slug": "battle-ram",
    "name": "Battle Ram",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Rare",
    "variant": "base"
  },
  {
    "id": "berserker",
    "slug": "berserker",
    "name": "Berserker",
    "elixir": 2,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "base"
  },
  {
    "id": "bomb-tower",
    "slug": "bomb-tower",
    "name": "Bomb Tower",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Building",
    "rarity": "Rare",
    "variant": "base"
  },
  {
    "id": "bomber",
    "slug": "bomber",
    "name": "Bomber",
    "elixir": 2,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "base"
  },
  {
    "id": "boss-bandit",
    "slug": "boss-bandit",
    "name": "Boss Bandit",
    "elixir": 6,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Champion",
    "variant": "base"
  },
  {
    "id": "bowler",
    "slug": "bowler",
    "name": "Bowler",
    "elixir": 5,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "cannon",
    "slug": "cannon",
    "name": "Cannon",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Building",
    "rarity": "Common",
    "variant": "base"
  },
  {
    "id": "cannon-cart",
    "slug": "cannon-cart",
    "name": "Cannon Cart",
    "elixir": 5,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "clone",
    "slug": "clone",
    "name": "Clone",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Spell",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "dark-prince",
    "slug": "dark-prince",
    "name": "Dark Prince",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "dart-goblin",
    "slug": "dart-goblin",
    "name": "Dart Goblin",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Rare",
    "variant": "base"
  },
  {
    "id": "earthquake",
    "slug": "earthquake",
    "name": "Earthquake",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Spell",
    "rarity": "Rare",
    "variant": "base"
  },
  {
    "id": "electro-dragon",
    "slug": "electro-dragon",
    "name": "Electro Dragon",
    "elixir": 5,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "electro-giant",
    "slug": "electro-giant",
    "name": "Electro Giant",
    "elixir": 7,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "electro-spirit",
    "slug": "electro-spirit",
    "name": "Electro Spirit",
    "elixir": 1,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "base"
  },
  {
    "id": "electro-wizard",
    "slug": "electro-wizard",
    "name": "Electro Wizard",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Legendary",
    "variant": "base"
  },
  {
    "id": "elite-barbarians",
    "slug": "elite-barbarians",
    "name": "Elite Barbarians",
    "elixir": 6,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "base"
  },
  {
    "id": "elixir-collector",
    "slug": "elixir-collector",
    "name": "Elixir Collector",
    "elixir": 6,
    "variable_elixir": false,
    "type": "Building",
    "rarity": "Rare",
    "variant": "base"
  },
  {
    "id": "elixir-golem",
    "slug": "elixir-golem",
    "name": "Elixir Golem",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Rare",
    "variant": "base"
  },
  {
    "id": "executioner",
    "slug": "executioner",
    "name": "Executioner",
    "elixir": 5,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "fire-spirit",
    "slug": "fire-spirit",
    "name": "Fire Spirit",
    "elixir": 1,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "base"
  },
  {
    "id": "fireball",
    "slug": "fireball",
    "name": "Fireball",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Spell",
    "rarity": "Rare",
    "variant": "base"
  },
  {
    "id": "firecracker",
    "slug": "firecracker",
    "name": "Firecracker",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "base"
  },
  {
    "id": "fisherman",
    "slug": "fisherman",
    "name": "Fisherman",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Legendary",
    "variant": "base"
  },
  {
    "id": "flying-machine",
    "slug": "flying-machine",
    "name": "Flying Machine",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Rare",
    "variant": "base"
  },
  {
    "id": "freeze",
    "slug": "freeze",
    "name": "Freeze",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Spell",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "furnace",
    "slug": "furnace",
    "name": "Furnace",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Building",
    "rarity": "Rare",
    "variant": "base"
  },
  {
    "id": "giant",
    "slug": "giant",
    "name": "Giant",
    "elixir": 5,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Rare",
    "variant": "base"
  },
  {
    "id": "giant-skeleton",
    "slug": "giant-skeleton",
    "name": "Giant Skeleton",
    "elixir": 6,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "giant-snowball",
    "slug": "giant-snowball",
    "name": "Giant Snowball",
    "elixir": 2,
    "variable_elixir": false,
    "type": "Spell",
    "rarity": "Common",
    "variant": "base"
  },
  {
    "id": "goblin-barrel",
    "slug": "goblin-barrel",
    "name": "Goblin Barrel",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Spell",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "goblin-cage",
    "slug": "goblin-cage",
    "name": "Goblin Cage",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Building",
    "rarity": "Rare",
    "variant": "base"
  },
  {
    "id": "goblin-curse",
    "slug": "goblin-curse",
    "name": "Goblin Curse",
    "elixir": 2,
    "variable_elixir": false,
    "type": "Spell",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "goblin-demolisher",
    "slug": "goblin-demolisher",
    "name": "Goblin Demolisher",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Rare",
    "variant": "base"
  },
  {
    "id": "goblin-drill",
    "slug": "goblin-drill",
    "name": "Goblin Drill",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Building",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "goblin-gang",
    "slug": "goblin-gang",
    "name": "Goblin Gang",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "base"
  },
  {
    "id": "goblin-giant",
    "slug": "goblin-giant",
    "name": "Goblin Giant",
    "elixir": 6,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "goblin-hut",
    "slug": "goblin-hut",
    "name": "Goblin Hut",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Building",
    "rarity": "Rare",
    "variant": "base"
  },
  {
    "id": "goblin-machine",
    "slug": "goblin-machine",
    "name": "Goblin Machine",
    "elixir": 5,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Legendary",
    "variant": "base"
  },
  {
    "id": "goblins",
    "slug": "goblins",
    "name": "Goblins",
    "elixir": 2,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "base"
  },
  {
    "id": "goblinstein",
    "slug": "goblinstein",
    "name": "Goblinstein",
    "elixir": 5,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Champion",
    "variant": "base"
  },
  {
    "id": "golden-knight",
    "slug": "golden-knight",
    "name": "Golden Knight",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Champion",
    "variant": "base"
  },
  {
    "id": "golem",
    "slug": "golem",
    "name": "Golem",
    "elixir": 8,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "graveyard",
    "slug": "graveyard",
    "name": "Graveyard",
    "elixir": 5,
    "variable_elixir": false,
    "type": "Spell",
    "rarity": "Legendary",
    "variant": "base"
  },
  {
    "id": "guards",
    "slug": "guards",
    "name": "Guards",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "heal-spirit",
    "slug": "heal-spirit",
    "name": "Heal Spirit",
    "elixir": 1,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Rare",
    "variant": "base"
  },
  {
    "id": "hog-rider",
    "slug": "hog-rider",
    "name": "Hog Rider",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Rare",
    "variant": "base"
  },
  {
    "id": "hunter",
    "slug": "hunter",
    "name": "Hunter",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "ice-golem",
    "slug": "ice-golem",
    "name": "Ice Golem",
    "elixir": 2,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Rare",
    "variant": "base"
  },
  {
    "id": "ice-spirit",
    "slug": "ice-spirit",
    "name": "Ice Spirit",
    "elixir": 1,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "base"
  },
  {
    "id": "ice-wizard",
    "slug": "ice-wizard",
    "name": "Ice Wizard",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Legendary",
    "variant": "base"
  },
  {
    "id": "inferno-dragon",
    "slug": "inferno-dragon",
    "name": "Inferno Dragon",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Legendary",
    "variant": "base"
  },
  {
    "id": "inferno-tower",
    "slug": "inferno-tower",
    "name": "Inferno Tower",
    "elixir": 5,
    "variable_elixir": false,
    "type": "Building",
    "rarity": "Rare",
    "variant": "base"
  },
  {
    "id": "knight",
    "slug": "knight",
    "name": "Knight",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "base"
  },
  {
    "id": "lava-hound",
    "slug": "lava-hound",
    "name": "Lava Hound",
    "elixir": 7,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Legendary",
    "variant": "base"
  },
  {
    "id": "lightning",
    "slug": "lightning",
    "name": "Lightning",
    "elixir": 6,
    "variable_elixir": false,
    "type": "Spell",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "little-prince",
    "slug": "little-prince",
    "name": "Little Prince",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Champion",
    "variant": "base"
  },
  {
    "id": "lumberjack",
    "slug": "lumberjack",
    "name": "Lumberjack",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Legendary",
    "variant": "base"
  },
  {
    "id": "magic-archer",
    "slug": "magic-archer",
    "name": "Magic Archer",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Legendary",
    "variant": "base"
  },
  {
    "id": "mega-knight",
    "slug": "mega-knight",
    "name": "Mega Knight",
    "elixir": 7,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Legendary",
    "variant": "base"
  },
  {
    "id": "mega-minion",
    "slug": "mega-minion",
    "name": "Mega Minion",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Rare",
    "variant": "base"
  },
  {
    "id": "mighty-miner",
    "slug": "mighty-miner",
    "name": "Mighty Miner",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Champion",
    "variant": "base"
  },
  {
    "id": "miner",
    "slug": "miner",
    "name": "Miner",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Legendary",
    "variant": "base"
  },
  {
    "id": "mini-pekka",
    "slug": "mini-pekka",
    "name": "Mini P.E.K.K.A",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Rare",
    "variant": "base"
  },
  {
    "id": "minion-horde",
    "slug": "minion-horde",
    "name": "Minion Horde",
    "elixir": 5,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "base"
  },
  {
    "id": "minions",
    "slug": "minions",
    "name": "Minions",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "base"
  },
  {
    "id": "mirror",
    "slug": "mirror",
    "name": "Mirror",
    "elixir": 0,
    "variable_elixir": true,
    "type": "Spell",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "monk",
    "slug": "monk",
    "name": "Monk",
    "elixir": 5,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Champion",
    "variant": "base"
  },
  {
    "id": "mortar",
    "slug": "mortar",
    "name": "Mortar",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Building",
    "rarity": "Common",
    "variant": "base"
  },
  {
    "id": "mother-witch",
    "slug": "mother-witch",
    "name": "Mother Witch",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Legendary",
    "variant": "base"
  },
  {
    "id": "musketeer",
    "slug": "musketeer",
    "name": "Musketeer",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Rare",
    "variant": "base"
  },
  {
    "id": "night-witch",
    "slug": "night-witch",
    "name": "Night Witch",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Legendary",
    "variant": "base"
  },
  {
    "id": "pekka",
    "slug": "pekka",
    "name": "P.E.K.K.A",
    "elixir": 7,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "phoenix",
    "slug": "phoenix",
    "name": "Phoenix",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Legendary",
    "variant": "base"
  },
  {
    "id": "poison",
    "slug": "poison",
    "name": "Poison",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Spell",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "prince",
    "slug": "prince",
    "name": "Prince",
    "elixir": 5,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "princess",
    "slug": "princess",
    "name": "Princess",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Legendary",
    "variant": "base"
  },
  {
    "id": "rage",
    "slug": "rage",
    "name": "Rage",
    "elixir": 2,
    "variable_elixir": false,
    "type": "Spell",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "ram-rider",
    "slug": "ram-rider",
    "name": "Ram Rider",
    "elixir": 5,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Legendary",
    "variant": "base"
  },
  {
    "id": "rascals",
    "slug": "rascals",
    "name": "Rascals",
    "elixir": 5,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "base"
  },
  {
    "id": "rocket",
    "slug": "rocket",
    "name": "Rocket",
    "elixir": 6,
    "variable_elixir": false,
    "type": "Spell",
    "rarity": "Rare",
    "variant": "base"
  },
  {
    "id": "royal-delivery",
    "slug": "royal-delivery",
    "name": "Royal Delivery",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Spell",
    "rarity": "Common",
    "variant": "base"
  },
  {
    "id": "royal-ghost",
    "slug": "royal-ghost",
    "name": "Royal Ghost",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Legendary",
    "variant": "base"
  },
  {
    "id": "royal-giant",
    "slug": "royal-giant",
    "name": "Royal Giant",
    "elixir": 6,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "base"
  },
  {
    "id": "royal-hogs",
    "slug": "royal-hogs",
    "name": "Royal Hogs",
    "elixir": 5,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Rare",
    "variant": "base"
  },
  {
    "id": "royal-recruits",
    "slug": "royal-recruits",
    "name": "Royal Recruits",
    "elixir": 7,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "base"
  },
  {
    "id": "rune-giant",
    "slug": "rune-giant",
    "name": "Rune Giant",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "skeleton-army",
    "slug": "skeleton-army",
    "name": "Skeleton Army",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "skeleton-barrel",
    "slug": "skeleton-barrel",
    "name": "Skeleton Barrel",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "base"
  },
  {
    "id": "skeleton-dragons",
    "slug": "skeleton-dragons",
    "name": "Skeleton Dragons",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "base"
  },
  {
    "id": "skeleton-king",
    "slug": "skeleton-king",
    "name": "Skeleton King",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Champion",
    "variant": "base"
  },
  {
    "id": "skeletons",
    "slug": "skeletons",
    "name": "Skeletons",
    "elixir": 1,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "base"
  },
  {
    "id": "sparky",
    "slug": "sparky",
    "name": "Sparky",
    "elixir": 6,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Legendary",
    "variant": "base"
  },
  {
    "id": "spear-goblins",
    "slug": "spear-goblins",
    "name": "Spear Goblins",
    "elixir": 2,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "base"
  },
  {
    "id": "spirit-empress",
    "slug": "spirit-empress",
    "name": "Spirit Empress",
    "elixir": 6,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Legendary",
    "variant": "base"
  },
  {
    "id": "suspicious-bush",
    "slug": "suspicious-bush",
    "name": "Suspicious Bush",
    "elixir": 2,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Rare",
    "variant": "base"
  },
  {
    "id": "tesla",
    "slug": "tesla",
    "name": "Tesla",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Building",
    "rarity": "Common",
    "variant": "base"
  },
  {
    "id": "the-log",
    "slug": "the-log",
    "name": "The Log",
    "elixir": 2,
    "variable_elixir": false,
    "type": "Spell",
    "rarity": "Legendary",
    "variant": "base"
  },
  {
    "id": "three-musketeers",
    "slug": "three-musketeers",
    "name": "Three Musketeers",
    "elixir": 9,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Rare",
    "variant": "base"
  },
  {
    "id": "tombstone",
    "slug": "tombstone",
    "name": "Tombstone",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Building",
    "rarity": "Rare",
    "variant": "base"
  },
  {
    "id": "tornado",
    "slug": "tornado",
    "name": "Tornado",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Spell",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "valkyrie",
    "slug": "valkyrie",
    "name": "Valkyrie",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Rare",
    "variant": "base"
  },
  {
    "id": "vines",
    "slug": "vines",
    "name": "Vines",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Spell",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "void",
    "slug": "void",
    "name": "Void",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Spell",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "wall-breakers",
    "slug": "wall-breakers",
    "name": "Wall Breakers",
    "elixir": 2,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "witch",
    "slug": "witch",
    "name": "Witch",
    "elixir": 5,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "wizard",
    "slug": "wizard",
    "name": "Wizard",
    "elixir": 5,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Rare",
    "variant": "base"
  },
  {
    "id": "x-bow",
    "slug": "x-bow",
    "name": "X-Bow",
    "elixir": 6,
    "variable_elixir": false,
    "type": "Building",
    "rarity": "Epic",
    "variant": "base"
  },
  {
    "id": "zap",
    "slug": "zap",
    "name": "Zap",
    "elixir": 2,
    "variable_elixir": false,
    "type": "Spell",
    "rarity": "Common",
    "variant": "base"
  },
  {
    "id": "zappies",
    "slug": "zappies",
    "name": "Zappies",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Rare",
    "variant": "base"
  },
  {
    "id": "archers--evo",
    "slug": "archers",
    "name": "Archers (Evolution)",
    "base_name": "Archers",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "evolution"
  },
  {
    "id": "baby-dragon--evo",
    "slug": "baby-dragon",
    "name": "Baby Dragon (Evolution)",
    "base_name": "Baby Dragon",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Epic",
    "variant": "evolution"
  },
  {
    "id": "barbarian-barrel--hero",
    "slug": "barbarian-barrel",
    "name": "Barbarian Barrel (Hero)",
    "base_name": "Barbarian Barrel",
    "elixir": 2,
    "variable_elixir": false,
    "type": "Spell",
    "rarity": "Hero",
    "variant": "hero"
  },
  {
    "id": "barbarians--evo",
    "slug": "barbarians",
    "name": "Barbarians (Evolution)",
    "base_name": "Barbarians",
    "elixir": 5,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "evolution"
  },
  {
    "id": "bats--evo",
    "slug": "bats",
    "name": "Bats (Evolution)",
    "base_name": "Bats",
    "elixir": 2,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "evolution"
  },
  {
    "id": "battle-ram--evo",
    "slug": "battle-ram",
    "name": "Battle Ram (Evolution)",
    "base_name": "Battle Ram",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Rare",
    "variant": "evolution"
  },
  {
    "id": "bomber--evo",
    "slug": "bomber",
    "name": "Bomber (Evolution)",
    "base_name": "Bomber",
    "elixir": 2,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "evolution"
  },
  {
    "id": "cannon--evo",
    "slug": "cannon",
    "name": "Cannon (Evolution)",
    "base_name": "Cannon",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Building",
    "rarity": "Common",
    "variant": "evolution"
  },
  {
    "id": "dart-goblin--evo",
    "slug": "dart-goblin",
    "name": "Dart Goblin (Evolution)",
    "base_name": "Dart Goblin",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Rare",
    "variant": "evolution"
  },
  {
    "id": "electro-dragon--evo",
    "slug": "electro-dragon",
    "name": "Electro Dragon (Evolution)",
    "base_name": "Electro Dragon",
    "elixir": 5,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Epic",
    "variant": "evolution"
  },
  {
    "id": "executioner--evo",
    "slug": "executioner",
    "name": "Executioner (Evolution)",
    "base_name": "Executioner",
    "elixir": 5,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Epic",
    "variant": "evolution"
  },
  {
    "id": "firecracker--evo",
    "slug": "firecracker",
    "name": "Firecracker (Evolution)",
    "base_name": "Firecracker",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "evolution"
  },
  {
    "id": "furnace--evo",
    "slug": "furnace",
    "name": "Furnace (Evolution)",
    "base_name": "Furnace",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Building",
    "rarity": "Rare",
    "variant": "evolution"
  },
  {
    "id": "giant--hero",
    "slug": "giant",
    "name": "Giant (Hero)",
    "base_name": "Giant",
    "elixir": 5,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Hero",
    "variant": "hero"
  },
  {
    "id": "giant-snowball--evo",
    "slug": "giant-snowball",
    "name": "Giant Snowball (Evolution)",
    "base_name": "Giant Snowball",
    "elixir": 2,
    "variable_elixir": false,
    "type": "Spell",
    "rarity": "Common",
    "variant": "evolution"
  },
  {
    "id": "goblin-barrel--evo",
    "slug": "goblin-barrel",
    "name": "Goblin Barrel (Evolution)",
    "base_name": "Goblin Barrel",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Spell",
    "rarity": "Epic",
    "variant": "evolution"
  },
  {
    "id": "goblin-cage--evo",
    "slug": "goblin-cage",
    "name": "Goblin Cage (Evolution)",
    "base_name": "Goblin Cage",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Building",
    "rarity": "Rare",
    "variant": "evolution"
  },
  {
    "id": "goblin-drill--evo",
    "slug": "goblin-drill",
    "name": "Goblin Drill (Evolution)",
    "base_name": "Goblin Drill",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Building",
    "rarity": "Epic",
    "variant": "evolution"
  },
  {
    "id": "goblin-giant--evo",
    "slug": "goblin-giant",
    "name": "Goblin Giant (Evolution)",
    "base_name": "Goblin Giant",
    "elixir": 6,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Epic",
    "variant": "evolution"
  },
  {
    "id": "goblins--hero",
    "slug": "goblins",
    "name": "Goblins (Hero)",
    "base_name": "Goblins",
    "elixir": 2,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Hero",
    "variant": "hero"
  },
  {
    "id": "hunter--evo",
    "slug": "hunter",
    "name": "Hunter (Evolution)",
    "base_name": "Hunter",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Epic",
    "variant": "evolution"
  },
  {
    "id": "ice-golem--hero",
    "slug": "ice-golem",
    "name": "Ice Golem (Hero)",
    "base_name": "Ice Golem",
    "elixir": 2,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Hero",
    "variant": "hero"
  },
  {
    "id": "ice-spirit--evo",
    "slug": "ice-spirit",
    "name": "Ice Spirit (Evolution)",
    "base_name": "Ice Spirit",
    "elixir": 1,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "evolution"
  },
  {
    "id": "inferno-dragon--evo",
    "slug": "inferno-dragon",
    "name": "Inferno Dragon (Evolution)",
    "base_name": "Inferno Dragon",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Legendary",
    "variant": "evolution"
  },
  {
    "id": "knight--evo",
    "slug": "knight",
    "name": "Knight (Evolution)",
    "base_name": "Knight",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "evolution"
  },
  {
    "id": "knight--hero",
    "slug": "knight",
    "name": "Knight (Hero)",
    "base_name": "Knight",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Hero",
    "variant": "hero"
  },
  {
    "id": "lumberjack--evo",
    "slug": "lumberjack",
    "name": "Lumberjack (Evolution)",
    "base_name": "Lumberjack",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Legendary",
    "variant": "evolution"
  },
  {
    "id": "magic-archer--hero",
    "slug": "magic-archer",
    "name": "Magic Archer (Hero)",
    "base_name": "Magic Archer",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Hero",
    "variant": "hero"
  },
  {
    "id": "mega-knight--evo",
    "slug": "mega-knight",
    "name": "Mega Knight (Evolution)",
    "base_name": "Mega Knight",
    "elixir": 7,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Legendary",
    "variant": "evolution"
  },
  {
    "id": "mega-minion--hero",
    "slug": "mega-minion",
    "name": "Mega Minion (Hero)",
    "base_name": "Mega Minion",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Hero",
    "variant": "hero"
  },
  {
    "id": "mini-pekka--hero",
    "slug": "mini-pekka",
    "name": "Mini P.E.K.K.A (Hero)",
    "base_name": "Mini P.E.K.K.A",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Hero",
    "variant": "hero"
  },
  {
    "id": "mortar--evo",
    "slug": "mortar",
    "name": "Mortar (Evolution)",
    "base_name": "Mortar",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Building",
    "rarity": "Common",
    "variant": "evolution"
  },
  {
    "id": "musketeer--evo",
    "slug": "musketeer",
    "name": "Musketeer (Evolution)",
    "base_name": "Musketeer",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Rare",
    "variant": "evolution"
  },
  {
    "id": "musketeer--hero",
    "slug": "musketeer",
    "name": "Musketeer (Hero)",
    "base_name": "Musketeer",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Hero",
    "variant": "hero"
  },
  {
    "id": "pekka--evo",
    "slug": "pekka",
    "name": "P.E.K.K.A (Evolution)",
    "base_name": "P.E.K.K.A",
    "elixir": 7,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Epic",
    "variant": "evolution"
  },
  {
    "id": "royal-ghost--evo",
    "slug": "royal-ghost",
    "name": "Royal Ghost (Evolution)",
    "base_name": "Royal Ghost",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Legendary",
    "variant": "evolution"
  },
  {
    "id": "royal-giant--evo",
    "slug": "royal-giant",
    "name": "Royal Giant (Evolution)",
    "base_name": "Royal Giant",
    "elixir": 6,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "evolution"
  },
  {
    "id": "royal-hogs--evo",
    "slug": "royal-hogs",
    "name": "Royal Hogs (Evolution)",
    "base_name": "Royal Hogs",
    "elixir": 5,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Rare",
    "variant": "evolution"
  },
  {
    "id": "royal-recruits--evo",
    "slug": "royal-recruits",
    "name": "Royal Recruits (Evolution)",
    "base_name": "Royal Recruits",
    "elixir": 7,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "evolution"
  },
  {
    "id": "skeleton-army--evo",
    "slug": "skeleton-army",
    "name": "Skeleton Army (Evolution)",
    "base_name": "Skeleton Army",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Epic",
    "variant": "evolution"
  },
  {
    "id": "skeleton-barrel--evo",
    "slug": "skeleton-barrel",
    "name": "Skeleton Barrel (Evolution)",
    "base_name": "Skeleton Barrel",
    "elixir": 3,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "evolution"
  },
  {
    "id": "skeletons--evo",
    "slug": "skeletons",
    "name": "Skeletons (Evolution)",
    "base_name": "Skeletons",
    "elixir": 1,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Common",
    "variant": "evolution"
  },
  {
    "id": "tesla--evo",
    "slug": "tesla",
    "name": "Tesla (Evolution)",
    "base_name": "Tesla",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Building",
    "rarity": "Common",
    "variant": "evolution"
  },
  {
    "id": "valkyrie--evo",
    "slug": "valkyrie",
    "name": "Valkyrie (Evolution)",
    "base_name": "Valkyrie",
    "elixir": 4,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Rare",
    "variant": "evolution"
  },
  {
    "id": "wall-breakers--evo",
    "slug": "wall-breakers",
    "name": "Wall Breakers (Evolution)",
    "base_name": "Wall Breakers",
    "elixir": 2,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Epic",
    "variant": "evolution"
  },
  {
    "id": "witch--evo",
    "slug": "witch",
    "name": "Witch (Evolution)",
    "base_name": "Witch",
    "elixir": 5,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Epic",
    "variant": "evolution"
  },
  {
    "id": "wizard--evo",
    "slug": "wizard",
    "name": "Wizard (Evolution)",
    "base_name": "Wizard",
    "elixir": 5,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Rare",
    "variant": "evolution"
  },
  {
    "id": "wizard--hero",
    "slug": "wizard",
    "name": "Wizard (Hero)",
    "base_name": "Wizard",
    "elixir": 5,
    "variable_elixir": false,
    "type": "Troop",
    "rarity": "Hero",
    "variant": "hero"
  },
  {
    "id": "zap--evo",
    "slug": "zap",
    "name": "Zap (Evolution)",
    "base_name": "Zap",
    "elixir": 2,
    "variable_elixir": false,
    "type": "Spell",
    "rarity": "Common",
    "variant": "evolution"
  }
];
